### ISSUE TITLE
Slippage Issue with Wheel Encoder Values 

### ISSUE THREAD

**Issue by SM-dot** [UCI-HyperXite/hx9-control-system#109]
Issue: Due to slippage - which means that when the wheel slips, it rotates less than it should for the actual distance traveled. 
Solution: Calculate the average distance from both the wheel encoders. So something like this - 
(Wheel Encoder 1 dist + Wheel Encoder 2 dist) / 2 > stop_threshold => pod stops

**Comment by taesungh** [comment]
Assuming the main source of slippage are the gaps between the track beams, taking the average at the end will provide nearly identical values among the two since both encoders would go through the same gaps. To actually account for one wheel under-spinning, we might need to compare the velocities of the two and then use the higher one to supplement the counter value.
